version: "3.4"

services:
  postgres:
    container_name: healers_db
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: healers
      POSTGRES_PASSWORD: password

volumes:
  postgres_data: