version: "3.4"

services:
  postgres:
    container_name: healers_db
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: healers
      POSTGRES_PASSWORD: password
  pgadmin:
    container_name: healers_pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "password"

volumes:
  postgres_data:
  pgadmin_data: